(function(root){
  'use strict';
  const intake=root.CVISADOS_INTAKE;
  const loaded=new Map();
  function loadScriptOnce(src,ready){if(ready?.())return Promise.resolve();if(loaded.has(src))return loaded.get(src);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>resolve();s.onerror=()=>reject(new Error(`No se pudo cargar ${src}`));document.head.appendChild(s)});loaded.set(src,p);return p}
  async function readUrl(url,{backendBase=''}={}){const metro=intake?.normalizeMetroLink(url)||{url:String(url||'')};if(!metro.url)return {ok:false,error:'Ingrese un ID o enlace Metro válido',record:{}};try{const r=await fetch(`${String(backendBase||'').replace(/\/$/,'')}/api/metro/read?url=${encodeURIComponent(metro.url)}`,{headers:{accept:'application/json'}});const data=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));if(!r.ok||!data.ok)return {ok:false,error:data.error||`HTTP ${r.status}`,url:metro.url,record:data.record||{}};return data}catch(err){return {ok:false,error:`El visor externo puede estar bloqueado y el backend no respondió: ${err.message}`,url:metro.url,record:{}}}}
  async function ensureTesseract(){await loadScriptOnce('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js',()=>!!root.Tesseract);if(!root.Tesseract)throw new Error('OCR no disponible');return root.Tesseract}
  async function ocrImage(image){const T=await ensureTesseract();const result=await T.recognize(image,'spa');return result?.data?.text||''}
  async function ensurePdfJs(){await loadScriptOnce('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js',()=>!!root.pdfjsLib);if(!root.pdfjsLib)throw new Error('Lector PDF OCR no disponible');root.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';return root.pdfjsLib}
  async function ocrPdf(file){const pdfjsLib=await ensurePdfJs(),T=await ensureTesseract(),bytes=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data:bytes}).promise;let text='';for(let i=1;i<=Math.min(pdf.numPages,5);i++){const page=await pdf.getPage(i),viewport=page.getViewport({scale:1.7}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const r=await T.recognize(canvas,'spa');text+=`\n${r?.data?.text||''}`}return text}
  async function readFile(file,{pdfTextExtractor}={}){if(!file)return {ok:false,error:'Seleccione un archivo',record:{},text:''};try{let text='';if(/^image\//i.test(file.type)||/\.(png|jpe?g|webp|bmp)$/i.test(file.name||''))text=await ocrImage(file);else if(file.type==='application/pdf'||/\.pdf$/i.test(file.name||'')){if(typeof pdfTextExtractor==='function')text=await pdfTextExtractor(file);if(String(text||'').replace(/\s/g,'').length<20)text=await ocrPdf(file)}else return {ok:false,error:'Formato no compatible. Use PDF o imagen.',record:{},text:''};return {ok:true,text,record:intake?.extractCaseFields(text)||{}}}catch(err){return {ok:false,error:String(err?.message||err),record:{},text:''}}}
  root.CVISADOS_READER={readUrl,readFile,ocrImage,ocrPdf};
})(typeof window!=='undefined'?window:globalThis);
