'use strict';
const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const intake=require('../js/intake.js');
const ROOT=path.resolve(__dirname,'..');
function isAllowedMetroUrl(raw){try{const u=new URL(String(raw||''));return u.protocol==='https:'&&u.hostname.toLowerCase()==='metro.sarapiqui.go.cr'}catch{return false}}
function htmlToText(html){return String(html||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:div|p|section|article|header|footer|li|tr|table|h[1-6])\s*>/gi,'\n').replace(/<\/(?:td|th)\s*>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#39;/gi,"'").replace(/&quot;/gi,'"').replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function htmlTitle(html){const m=String(html||'').match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?htmlToText(m[1]):''}
async function scrapeMetro(url,{fetchImpl=globalThis.fetch,timeoutMs=15000}={}){if(!isAllowedMetroUrl(url))throw new Error('URL Metro no permitida');if(typeof fetchImpl!=='function')throw new Error('Fetch no disponible');const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),timeoutMs);try{const r=await fetchImpl(url,{redirect:'follow',signal:ctrl.signal,headers:{'user-agent':'C-VISADOS/3.7.1 Metro Reader','accept':'text/html,application/xhtml+xml'}});if(!r.ok)throw new Error(`Metro respondió HTTP ${r.status}`);const finalUrl=r.url||url;if(!isAllowedMetroUrl(finalUrl))throw new Error('Redirección fuera de Metro no permitida');const html=await r.text(),text=htmlToText(html);return {ok:true,url:finalUrl,title:htmlTitle(html),text,record:intake.extractCaseFields(text)}}finally{clearTimeout(timer)}}
function contentType(p){const ext=path.extname(p).toLowerCase();return ({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}[ext]||'application/octet-stream')}
function sendJson(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'content-type'});res.end(JSON.stringify(obj))}
function createServer({root=ROOT,fetchImpl=globalThis.fetch}={}){return http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,OPTIONS','access-control-allow-headers':'content-type'});return res.end()}const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/health')return sendJson(res,200,{ok:true,service:'c-visados',version:'3.7.1'});if(u.pathname==='/api/metro/read'){const target=u.searchParams.get('url')||'';if(!isAllowedMetroUrl(target))return sendJson(res,400,{ok:false,error:'URL Metro inválida o no permitida'});try{return sendJson(res,200,await scrapeMetro(target,{fetchImpl}))}catch(err){return sendJson(res,502,{ok:false,error:String(err?.message||err)})}}
 let rel=decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname).replace(/^\/+/,''),file=path.resolve(root,rel);if(!file.startsWith(path.resolve(root)+path.sep)&&file!==path.resolve(root,'index.html')){res.writeHead(403);return res.end('Forbidden')}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':contentType(file)});fs.createReadStream(file).pipe(res)}catch(err){sendJson(res,500,{ok:false,error:'Error interno'})}})}
if(require.main===module){const port=Number(process.env.PORT||8787),server=createServer();server.listen(port,()=>console.log(`C-VISADOS 3.7.1: http://localhost:${port}`))}
module.exports={isAllowedMetroUrl,htmlToText,scrapeMetro,createServer};
